
#Desenvolvimento
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: softcon

#produção
# development:
#   adapter: postgresql
#   encoding: unicode
#   database: softcon
#   host: 162.243.171.44
#   pool: 5
#   username: deploy
#   password: bcoambar
#   port: 5432
